POST  http://127.0.0.1:4000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "rfc": "XDOTRORPRUEBA",
    "first_name": "Fernando",
    "last_name": "Guerrero",
    "nip": "0909",
    "tipo_cuenta": "Personal"

}

###

POST http://127.0.0.1:4000/api/users/deleteAccount HTTP/1.1
Content-Type: application/json

{
    "account_number": "4152789932238476"
}

###

POST  http://127.0.0.1:4000/api/users/rfc HTTP/1.1
Content-Type: application/json

{
    "rfc": "HEAE030929JKL"
}

###

POST http://127.0.0.1:4000/api/users/transfer HTTP/1.1
Content-Type: application/json

{
    "cuenta_origen": "4152592406905511",
    "cuenta_destino": "",
    "monto": "500"
}

###

POST http://127.0.0.1:4000/api/users/deposit HTTP/1.1
Content-Type: application/json

{
    "cuenta_origen": "4152592406905511",
    "monto": "500"
}

###

POST http://127.0.0.1:4000/api/users/withdraw HTTP/1.1
Content-Type: application/json

{
    "cuenta_origen": "4152970488681747",
    "monto": "1500"
}

###

GET http://127.0.0.1:4000/api/users/ HTTP/1.1

###GET PERSONAL ACCOUNT

GET http://127.0.0.1:4000/api/users/personal/11 HTTP/1.1

###GET EMPRESARIAL ACCOUNT

GET http://127.0.0.1:4000/api/users/empresarial/1 HTTP/1.1

