GET  http://127.0.0.1:4000/api/users/7 HTTP/1.1
Content-Type: application/json

{
    "rfc": "XDOTRORFC1000",
    "first_name": "Fernando",
    "last_name": "Guerrero",
    "nip": "0909",
    "tipo_cuenta": "Personal"

}